[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "freetype", "libjpeg", "libwebp", "zlib"]

[phases.install]
cmds = ["pip install -r bot/requirements.txt"]

[start]
cmd = "cd bot && python3 main.py"
